---
run:
  timeout: 5m
  concurrency: 0

output:
  sort-results: true
  print-issued-lines: true
  print-linter-name: true
  show-stats: true
  sort-order:
    - linter
    - severity
    - file

linters:
  enable:
    - durationcheck
    - errname
    - errorlint
    - copyloopvar
    - gocognit
    - gocritic
    - gofmt    
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - wastedassign
  disable:
    - unused
    - gofumpt

linters-settings:
  gocognit:
    min-complexity: 50
  gocritic:
    disabled-checks:
      - commentFormatting
      - commentedOutCode
    enabled-tags:
      - style 
      - diagnostic
      - performance
  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  max-same-issues: 0
  uniq-by-line: true
  new: false
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - govet
        - structcheck
  exclude-files:
    # Skip autogenerated files.
    - ^.*\.(pb|y)\.go$
